sudo: false
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "dev"
env:
  global:
    - COVERAGE=1
cache:
  directories:
    - $HOME/perl5/perlbrew/perls/$TRAVIS_PERL_VERSION/bin/
    - $HOME/perl5/perlbrew/perls/$TRAVIS_PERL_VERSION/lib/site_perl/
before_cache:
    - perlbrew list
    - set | grep -a 'PERL.*='
matrix:
  allow_failures:
    - perl: dev
before_install:
  - cpanp x
  - eval $(curl https://travis-perl.github.io/init) --auto
